### ISSUE TITLE
sub-pages not rendering

### ISSUE THREAD

**Issue by Jaff** [mhartl/sample_css#1]
Working through tutorial, I found that when adding the gallery directory and simple index.html, I did not get expected content rendered (jekyll server was running) instead I got error in console:
[2017-07-05 01:45:46] ERROR `/gallery/css/main.css' not found.
And the rendered page contained header, footer and text of index (I'm a 3-col page!)

I should have mentioned, running on OS X 10.11.6.

**Comment by mhartl** [comment]
As far as I can tell, your code includes 
```
<link rel="stylesheet" href="/main.css">
```
whereas all the examples in the tutorial use
```
<link rel="stylesheet" href="/css/main.css">
```
Perhaps that's the source of the discrepancy?

**Comment by Jaff** [comment]
Oh! Let me try that, thanks.

**Comment by marcluettecke** [comment]
Dear Michael,

thanks for the amazing tutorial, it's my first shot at HTML and CSS. Could you give me some idea, why my pages are not rendering (just like Jaff above I can't get the main.css script to apply the styling to the gallery page). I do have the <link rel="stylesheet" href="/main.css"> in place in the head, but that was the only way for me to even get the GitHub page render the styling even to the homepage.

Working with Jekyll the local rendering works great, but as I said my GitHub page only allows for the homepage to be formatted according to the main.css file. My set up follows mainly your instructions, but I do have some additional folders since I used Jekyll to set up the initial folder structure. and tried to adjust the _config.yml file so that it allows for the correct GitHub integration. The operating system is Windows 10.

The relevant repository is CSS_guide_Jekyll1

Thanks in advance and let me know if you need any more information to see where I'm coming from.

Best,

Marc

**Comment by mhartl** [comment]
To get CSS inclusion in sub-directories, you have to be using absolute paths (/path/to/css_file.css) and <username>.github.io or a custom domain. If you're not using such paths or such a domain, that might be the source of the problem.

**Comment by marcluettecke** [comment]
Hi Michael,

thanks for the quick response and also thanks for the amazing tutorials. After 2 days and consulting numerous websites, I was able to set things up for my local machine, as well as for GitHub, so I figured it might make sense, I give a couple of hints on what were major problems in the process:

1. To be able to render CSS in your local machine, via Jekyll, as well as on GitHub, you need to configure the _congif.yml file, which was automatically created (https://jekyllrb.com/docs/) for a new project / blog
   1.1 Set the baseurl to your GitHub project, for example, my project was called "CSS_guide_Jekyll", so I 
         had to put "/CSS_guide_Jekyll" (not in quotes) in there.
   1.2 Set the url to your GitHub page, so for my account, this would be "https://github.com/m1gnoc" 
         (once again without quotes)
2. Now came the tricky part for me: to render it virtually, you need to include {{ site.baseurl }} before every reference to your root directory. This means that for example to make your CSS file link to your index file via the <head> you type (if your CSS file is calles "main" and lies within the folder named "css" in your root directory):

<head>
<link href="{{ site.baseurl }}/css/main.css" rel="stylesheet">
</head>

This has to be done analogously for images, or anything else you want to link to.

3. To display your website locally via Atom and Jekyll, start the Jekyll server disregarding the base-url that you have defined above (this setting was explicitly made to have your GitHub page work). So in your Command prompt type (for windows): 
jekyll serve --baseurl

4. One last thing: some styling options did not render correctly anymore, so for example for this tutorial we used a shark.png as background and styled it in the CSS file. I found it only to work, once I had the styling done in the index file itself as part of the <div>.

I hope this helps some lost souls and that you don't need to spend 2 days of your life reading up on it, to get it going. 

Best of luck and once again, thanks Michale, for the amazing tutorials!

Marc

**Comment by mhartl** [comment]
Thanks for the details. Glad you got it working!
